# Generated by Django 4.1.3 on 2022-11-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0002_rename_center_zenotiemployeesdata_center"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zenotiemployeesdata",
            name="center",
        ),
        migrations.AddField(
            model_name="zenotiemployeesdata",
            name="center",
            field=models.ManyToManyField(
                blank=True, null=True, to="body_craft_app.zenoticentersdata"
            ),
        ),
    ]
