# Generated by Django 4.1.3 on 2022-11-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0003_remove_zenotiemployeesdata_center_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zenotiemployeesdata",
            name="center",
            field=models.ManyToManyField(
                blank=True, to="body_craft_app.zenoticentersdata"
            ),
        ),
    ]
