# Generated by Django 4.1.3 on 2022-11-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0005_remove_zenotiemployeesdata_center"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zenotiemployeesdata",
            name="center_code",
        ),
        migrations.RemoveField(
            model_name="zenotiemployeesdata",
            name="zenoticenterId",
        ),
    ]
