# Generated by Django 4.1.3 on 2022-11-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0007_associated_role_options_week_off_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WEEK_OFF_OPTIONS",
            new_name="AssociatedRoleOptions",
        ),
        migrations.RenameModel(
            old_name="ASSOCIATED_ROLE_OPTIONS",
            new_name="WeekOffOptions",
        ),
    ]
