# Generated by Django 4.1.3 on 2022-11-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "body_craft_app",
            "0008_rename_week_off_options_associatedroleoptions_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedzenotiemployeesdata",
            name="associated_role",
            field=models.ManyToManyField(
                blank=True, to="body_craft_app.associatedroleoptions"
            ),
        ),
        migrations.AlterField(
            model_name="extendedzenotiemployeesdata",
            name="week_off",
            field=models.ManyToManyField(
                blank=True, to="body_craft_app.weekoffoptions"
            ),
        ),
    ]
