# Generated by Django 3.2.13 on 2022-11-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0010_employee_roster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_roster',
            new_name='EmployeeRoster',
        ),
    ]
