# Generated by Django 3.2.13 on 2022-11-09 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0011_rename_employee_roster_employeeroster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeroster',
            name='associated_role',
        ),
        migrations.AddField(
            model_name='employeeroster',
            name='associated_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='body_craft_app.associatedroleoptions'),
        ),
    ]
