# Generated by Django 3.2.13 on 2022-11-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0012_auto_20221110_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeroster',
            name='appoint_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
