# Generated by Django 4.1.3 on 2022-11-15 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0013_alter_employeeroster_appoint_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtendedZenotiCenterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "closing_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "closed_on",
                    models.ManyToManyField(
                        blank=True, to="body_craft_app.weekoffoptions"
                    ),
                ),
                (
                    "zenoti_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="body_craft_app.zenoticentersdata",
                    ),
                ),
            ],
        ),
    ]
