# Generated by Django 4.1.3 on 2022-11-16 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0014_extendedzenoticenterdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtendedZenotiEmployeesLeaveData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_from_date", models.DateField(blank=True, null=True)),
                ("leave_to_date", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Approved", "Approved"),
                            ("Pending", "Pending"),
                            ("Rejected", "Rejected"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "zenoti_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="body_craft_app.zenotiemployeesdata",
                    ),
                ),
            ],
        ),
    ]
