# Generated by Django 4.1.3 on 2022-11-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0016_alter_extendedzenoticenterdata_zenoti_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeScheduler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=200, null=True)),
                ("appoint_date", models.DateField(blank=True, null=True)),
                (
                    "office_start_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "office_end_time",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "associated_role",
                    models.ManyToManyField(
                        blank=True, null=True, to="body_craft_app.associatedroleoptions"
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="body_craft_app.zenoticentersdata",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="body_craft_app.zenotiemployeesdata",
                    ),
                ),
            ],
        ),
    ]
