# Generated by Django 4.1.3 on 2022-11-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0017_employeescheduler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeescheduler",
            name="associated_role",
            field=models.ManyToManyField(
                blank=True, to="body_craft_app.associatedroleoptions"
            ),
        ),
    ]
