# Generated by Django 4.1.3 on 2022-11-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0018_alter_employeescheduler_associated_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeescheduler",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Available", "Available"),
                    ("Week Off", "Week Off"),
                    ("Leave Request", "Leave Request"),
                    ("Leave Approved", "Leave Approved"),
                    ("Unplanned Leave", "Unplanned Leave"),
                    ("Training/Meeting", "Training/Meeting"),
                    ("Floating Resource", "Floating Resource"),
                    ("Internal Transfer", "Internal Transfer"),
                    ("Exit", "Exit"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
