# Generated by Django 4.1.3 on 2022-11-18 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0019_alter_employeescheduler_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeescheduler",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="body_craft_app.extendedzenotiemployeesdata",
            ),
        ),
    ]
