# Generated by Django 4.1.3 on 2022-11-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0022_operationoption_sectionoption_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedzenotiemployeesdata",
            name="position",
            field=models.ManyToManyField(blank=True, to="body_craft_app.position"),
        ),
    ]
