# Generated by Django 3.2.13 on 2022-11-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0024_remove_extendedzenotiemployeesdata_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeroster',
            name='associated_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='body_craft_app.position'),
        ),
    ]
