# Generated by Django 3.2.13 on 2022-11-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0025_alter_employeeroster_associated_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='zenotiemployeesdata',
            name='zenoti_center',
            field=models.ManyToManyField(blank=True, to='body_craft_app.ZenotiCentersData'),
        ),
    ]
