# Generated by Django 4.1.3 on 2022-11-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0026_zenotiemployeesdata_zenoti_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedzenotiemployeesdata",
            name="is_manager",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
