# Generated by Django 4.1.3 on 2022-11-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0027_extendedzenotiemployeesdata_is_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedzenotiemployeesdata",
            name="password",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
