# Generated by Django 3.2.13 on 2022-12-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0029_alter_employeeroster_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeescheduler',
            name='associated_role',
            field=models.ManyToManyField(blank=True, to='body_craft_app.Position'),
        ),
        migrations.AlterField(
            model_name='extendedzenotiemployeesdata',
            name='associated_role',
            field=models.ManyToManyField(blank=True, to='body_craft_app.Position'),
        ),
    ]
