# Generated by Django 3.2.13 on 2022-12-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0030_auto_20221202_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedzenotiemployeesdata',
            name='associated_center',
            field=models.ManyToManyField(blank=True, to='body_craft_app.ExtendedZenotiCenterData'),
        ),
    ]
