# Generated by Django 3.2.13 on 2022-12-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0031_alter_extendedzenotiemployeesdata_associated_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
