# Generated by Django 3.2.13 on 2022-12-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0035_auto_20221216_0229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MysteryShoppingOverview',
        ),
    ]
