# Generated by Django 3.2.13 on 2023-01-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0037_auto_20230102_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeescheduler',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
