# Generated by Django 3.2.13 on 2023-01-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0038_employeescheduler_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=200, null=True),
        ),
    ]
