# Generated by Django 3.2.13 on 2023-01-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0039_userprofile_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('staff', 'staff'), ('admin', 'admin'), ('Audit Admin', 'Audit Admin'), ('Mystery Shopper', 'Mystery Shopper'), ('Salon Revenue Auditor', 'Salon Revenue Auditor')], max_length=100),
        ),
    ]
