# Generated by Django 3.2.13 on 2023-03-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0042_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_category',
            field=models.CharField(blank=True, choices=[('staff', 'staff'), ('admin', 'admin'), ('Auditor', 'Auditor'), ('Audit Admin', 'Audit Admin'), ('Mystery Shopper', 'Mystery Shopper'), ('Salon Revenue Auditor', 'Salon Revenue Auditor'), ('Clinic Revenue Auditor', 'Clinic Revenue Auditor'), ('Corporate Auditor', 'Corporate Auditor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('staff', 'staff'), ('admin', 'admin'), ('Auditor', 'Auditor'), ('Audit Admin', 'Audit Admin'), ('Mystery Shopper', 'Mystery Shopper'), ('Salon Revenue Auditor', 'Salon Revenue Auditor'), ('Clinic Revenue Auditor', 'Clinic Revenue Auditor'), ('Corporate Auditor', 'Corporate Auditor')], max_length=100),
        ),
    ]
