# Generated by Django 3.2.13 on 2023-03-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0044_auto_20230306_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserType',
            new_name='UserTypes',
        ),
    ]
