# Generated by Django 3.2.13 on 2023-03-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body_craft_app', '0045_rename_usertype_usertypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertypes',
            name='unique_id',
        ),
    ]
