# Generated by Django 4.1.3 on 2023-03-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0046_remove_usertypes_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedzenoticenterdata",
            name="center_status",
            field=models.CharField(
                blank=True,
                choices=[("Active", "Active"), ("InActive", "InActive")],
                default="Active",
                max_length=200,
                null=True,
            ),
        ),
    ]
