# Generated by Django 4.1.3 on 2023-03-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0048_errorlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="roster_access",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
