# Generated by Django 4.1.3 on 2023-03-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0049_userprofile_roster_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="roster_access",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
