# Generated by Django 4.1.3 on 2023-03-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0051_alter_errorlog_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorlog",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
