# Generated by Django 4.1.3 on 2022-12-17 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("body_craft_app", "0036_delete_mysteryshoppingoverview"),
        ("mystery_shopping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MysteryShoppingDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "client_journey",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("kra", models.CharField(blank=True, max_length=200, null=True)),
                ("process", models.CharField(blank=True, max_length=200, null=True)),
                ("checklist", models.CharField(blank=True, max_length=1000, null=True)),
                ("Compliance", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "relative_gaps_found",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("remark", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "action_taken_by_outlet_manager",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status_by_om",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "remark_by_om",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "action_taken_by_management",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "remark_by_management",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "expected_dept_intervene",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "remark_by_department",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "status_by_department",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="body_craft_app.extendedzenoticenterdata",
                    ),
                ),
                (
                    "mystery_shopping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mystery_shopping.mysteryshoppingoverview",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="body_craft_app.extendedzenotiemployeesdata",
                    ),
                ),
            ],
        ),
    ]
