# Generated by Django 4.1.3 on 2022-12-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystery_shopping", "0003_rename_compliance_mysteryshoppingdetail_compliance"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysteryshoppingdetail",
            name="sequence",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
