# Generated by Django 4.1.3 on 2022-12-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystery_shopping", "0004_mysteryshoppingdetail_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysteryshoppingdetail",
            name="compliance_dropdown",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
