# Generated by Django 3.2.13 on 2022-12-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystery_shopping', '0006_mysteryshoppingdetail_compliance_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysteryshoppingdetail',
            name='service_availed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
