# Generated by Django 3.2.13 on 2022-12-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystery_shopping', '0007_mysteryshoppingdetail_service_availed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysteryshoppingdetail',
            name='compliance_category_percentage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
