# Generated by Django 3.2.13 on 2022-12-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystery_shopping', '0008_mysteryshoppingdetail_compliance_category_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysteryshoppingoverview',
            name='amount_in_cash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mysteryshoppingoverview',
            name='amount_redeemed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mysteryshoppingoverview',
            name='contact_number_reached_for_appointment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mysteryshoppingoverview',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
