# Generated by Django 4.1.3 on 2022-12-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystery_shopping", "0010_mysteryshoppingimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mysteryshoppingimages",
            name="image",
            field=models.ImageField(
                blank=True, default="profile1.jpg", null=True, upload_to="media"
            ),
        ),
    ]
