# Generated by Django 3.2.13 on 2022-12-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystery_shopping', '0011_alter_mysteryshoppingimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysteryshoppingoverview',
            name='amount_in_cash',
        ),
    ]
