# Generated by Django 3.2.13 on 2023-01-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystery_shopping', '0014_auto_20230117_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysteryshoppingdetail',
            name='service_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
