# Generated by Django 3.2.13 on 2023-01-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystery_shopping', '0015_mysteryshoppingdetail_service_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysteryshoppingoverview',
            name='service_availed_1',
        ),
    ]
