# Generated by Django 3.2.13 on 2023-01-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystery_shopping', '0017_auto_20230117_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysteryshoppingimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
