# Generated by Django 3.2.13 on 2023-02-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystery_shopping', '0018_alter_mysteryshoppingimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysteryshoppingdetail',
            name='service_availed_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mysteryshoppingdetail',
            name='service_availed_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mysteryshoppingdetail',
            name='service_availed_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
