# Generated by Django 3.2.13 on 2023-02-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystery_shopping', '0019_auto_20230213_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mysteryshoppingoverview',
            name='month_of_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystery_shopping.monthaudit'),
        ),
    ]
