# Generated by Django 3.2.13 on 2023-02-13 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystery_shopping', '0020_auto_20230213_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysteryshoppingoverview',
            name='month_of_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystery_shopping.monthaudit'),
        ),
    ]
