# Generated by Django 3.2.13 on 2023-02-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystery_shopping', '0021_alter_mysteryshoppingoverview_month_of_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysteryshoppingdetail',
            name='audit_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mysteryshoppingdetail',
            name='comment_for_auditor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
