# Generated by Django 3.2.13 on 2023-01-15 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('body_craft_app', '0038_employeescheduler_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonRevenueAuditOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('auditor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('audit_period', models.CharField(blank=True, max_length=500, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('physical_cash_as_per_zenoti', models.IntegerField(blank=True, null=True)),
                ('physical_cash_as_per_counter', models.IntegerField(blank=True, null=True)),
                ('physical_cash_reconciliation', models.IntegerField(blank=True, null=True)),
                ('physcial_card_as_per_zenoti', models.IntegerField(blank=True, null=True)),
                ('physcial_card_as_per_counter', models.IntegerField(blank=True, null=True)),
                ('physcial_card_reconciliation', models.IntegerField(blank=True, null=True)),
                ('custom_verification_as_per_zenoti', models.IntegerField(blank=True, null=True)),
                ('custom_verification_as_per_counter', models.IntegerField(blank=True, null=True)),
                ('custom_verification_reconciliation', models.IntegerField(blank=True, null=True)),
                ('ob_as_per_statement', models.IntegerField(blank=True, null=True)),
                ('ob_as_per_pv', models.IntegerField(blank=True, null=True)),
                ('closing_balance_as_per_zenoti', models.IntegerField(blank=True, null=True)),
                ('cash_in_hand', models.IntegerField(blank=True, null=True)),
                ('balance_in_happy_card', models.IntegerField(blank=True, null=True)),
                ('voucher_not_accounted_in_zenoti_value', models.IntegerField(blank=True, null=True)),
                ('rectification_tracker_maintained', models.IntegerField(blank=True, null=True)),
                ('rectification_tracker_updated', models.IntegerField(blank=True, null=True)),
                ('no_of_rectification_bill_as_per_zenoti', models.IntegerField(blank=True, null=True)),
                ('no_of_rectification_bill_as_per_tracker', models.IntegerField(blank=True, null=True)),
                ('no_of_rectification_approved_by_om', models.IntegerField(blank=True, null=True)),
                ('total_no_of_nearby_transaction_in_zenoti', models.IntegerField(blank=True, null=True)),
                ('remarks_with_voucher_number', models.IntegerField(blank=True, null=True)),
                ('without_voucher_number', models.IntegerField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='body_craft_app.userprofile')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='body_craft_app.extendedzenoticenterdata')),
            ],
        ),
        migrations.CreateModel(
            name='SalonAuditRepeatedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.CharField(blank=True, max_length=500, null=True)),
                ('responsible_kra', models.CharField(blank=True, max_length=200, null=True)),
                ('relative_gap_found', models.CharField(blank=True, max_length=500, null=True)),
                ('compliance', models.CharField(blank=True, max_length=200, null=True)),
                ('compliance_category', models.CharField(blank=True, max_length=200, null=True)),
                ('compliance_category_percentage', models.CharField(blank=True, max_length=20, null=True)),
                ('action_taken_by_outlet_manager', models.CharField(blank=True, max_length=200, null=True)),
                ('status_by_om', models.CharField(blank=True, max_length=200, null=True)),
                ('remark_by_om', models.CharField(blank=True, max_length=1000, null=True)),
                ('action_taken_by_management', models.CharField(blank=True, max_length=200, null=True)),
                ('remark_by_management', models.CharField(blank=True, max_length=1000, null=True)),
                ('expected_dept_intervene', models.CharField(blank=True, max_length=200, null=True)),
                ('remark_by_department', models.CharField(blank=True, max_length=1000, null=True)),
                ('status_by_department', models.CharField(blank=True, max_length=200, null=True)),
                ('person_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='body_craft_app.extendedzenotiemployeesdata')),
                ('revenue_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon_revenue_audit', to='salon_revenue_audit.salonrevenueauditoverview')),
            ],
        ),
        migrations.CreateModel(
            name='HygieneAnnexure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_dates', models.CharField(blank=True, max_length=500, null=True)),
                ('total_guest', models.CharField(blank=True, max_length=500, null=True)),
                ('sample_size_for_audit', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=500, null=True)),
                ('reception_copy', models.CharField(blank=True, max_length=200, null=True)),
                ('security_copy', models.CharField(blank=True, max_length=200, null=True)),
                ('security_sheet', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback_updated', models.CharField(blank=True, max_length=200, null=True)),
                ('was_the_rating_above_4', models.CharField(blank=True, max_length=200, null=True)),
                ('if_no_was_the_im_created', models.CharField(blank=True, max_length=200, null=True)),
                ('job_card_attached', models.CharField(blank=True, max_length=200, null=True)),
                ('job_card_matches_invoice', models.CharField(blank=True, max_length=200, null=True)),
                ('sa_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('revenue_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salon_revenue_audit.salonrevenueauditoverview')),
            ],
        ),
    ]
