# Generated by Django 3.2.13 on 2023-01-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_revenue_audit', '0003_auto_20230119_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hygieneannexure',
            name='sample_dates',
            field=models.DateField(blank=True, max_length=500, null=True),
        ),
    ]
