# Generated by Django 3.2.13 on 2023-01-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_revenue_audit', '0004_alter_hygieneannexure_sample_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hygieneannexure',
            name='sample_dates',
            field=models.DateField(blank=True, null=True),
        ),
    ]
