# Generated by Django 3.2.13 on 2023-01-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_revenue_audit', '0006_auto_20230120_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='no_of_blockout_notes_active',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='no_of_blockout_notes_deleted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
