# Generated by Django 3.2.13 on 2023-01-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_revenue_audit', '0007_auto_20230120_0420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salonrevenueauditoverview',
            old_name='no_of_clients_on_floor',
            new_name='audit_sample_size',
        ),
        migrations.RenameField(
            model_name='salonrevenueauditoverview',
            old_name='no_of_open_bill',
            new_name='no_of_appointment_as_per_zenoti_row_one',
        ),
        migrations.RenameField(
            model_name='salonrevenueauditoverview',
            old_name='no_of_rectification_approved_by_om',
            new_name='no_of_appointment_as_per_zenoti_row_two',
        ),
        migrations.RenameField(
            model_name='salonrevenueauditoverview',
            old_name='no_of_rectification_bill_as_per_tracker',
            new_name='no_of_clients_on_floor_row_one',
        ),
        migrations.RenameField(
            model_name='salonrevenueauditoverview',
            old_name='rectification_tracker_maintained',
            new_name='no_of_clients_on_floor_row_two',
        ),
        migrations.RenameField(
            model_name='salonrevenueauditoverview',
            old_name='voucher_not_accounted_in_zenoti_value',
            new_name='no_of_issues_as_per_zenoti_for_rectification_bill',
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='blockout_remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='dcr_cash_deposited',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='dcr_updated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='no_of_open_bill_row_one',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='no_of_open_bill_row_two',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='no_of_otp_overrides_as_per_zenoti',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='no_of_voucher_updated_on_zenoti',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='ob_remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='om_approved_otp_overrides',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='open_bill_remark_row_one',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='open_bill_remark_row_two',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='otp_override_remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='petty_cash_remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='physical_voucher_available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='pushed_appointment_remark_row_one',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='pushed_appointment_remark_row_two',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='total_no_of_audit_sample',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='total_no_of_membership_redeemed_for_campaign',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salonrevenueauditoverview',
            name='rectification_tracker_updated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salonrevenueauditoverview',
            name='without_voucher_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
