# Generated by Django 4.1.3 on 2023-01-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon_revenue_audit", "0008_auto_20230121_0212"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonrevenueauditoverview",
            name="open_bill_audit_row_one",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="salonrevenueauditoverview",
            name="open_bill_audit_row_two",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="salonrevenueauditoverview",
            name="pushed_appointment_audit_period_row_one",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="salonrevenueauditoverview",
            name="pushed_appointment_audit_period_row_two",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
