# Generated by Django 4.1.3 on 2023-01-21 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "salon_revenue_audit",
            "0010_alter_salonrevenueauditoverview_audit_sample_size_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedServiceAnnexure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "no_of_services_deleted",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "deleted_without_justification",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "revenue_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salon_revenue_audit.salonrevenueauditoverview",
                    ),
                ),
            ],
        ),
    ]
