# Generated by Django 3.2.13 on 2023-01-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_revenue_audit', '0012_rectificationbillannexure'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonrevenueauditoverview',
            name='dcr_remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
