# Generated by Django 3.2.13 on 2023-01-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon_revenue_audit', '0013_salonrevenueauditoverview_dcr_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignOfferAnnexure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_request', models.CharField(blank=True, max_length=500, null=True)),
                ('date_of_redemption', models.CharField(blank=True, max_length=500, null=True)),
                ('client_name', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=500, null=True)),
                ('guest_code', models.CharField(blank=True, max_length=500, null=True)),
                ('voucher_value', models.CharField(blank=True, max_length=500, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('revenue_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salon_revenue_audit.salonrevenueauditoverview')),
            ],
        ),
    ]
