# Generated by Django 4.1.3 on 2023-01-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("salon_revenue_audit", "0014_campaignofferannexure"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherObservationAnnexure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation_area",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "audit_findings",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "revenue_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salon_revenue_audit.salonrevenueauditoverview",
                    ),
                ),
            ],
        ),
    ]
