# Generated by Django 4.1.3 on 2023-01-26 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("salon_revenue_audit", "0015_otherobservationannexure"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoucherAnnexure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_request",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "date_of_redemption",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("guest_code", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "voucher_value",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("remark", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "revenue_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salon_revenue_audit.salonrevenueauditoverview",
                    ),
                ),
            ],
        ),
    ]
