# Generated by Django 4.1.3 on 2023-01-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon_revenue_audit", "0016_voucherannexure"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonrevenueauditoverview",
            name="petty_cash_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
