# Generated by Django 4.1.3 on 2023-01-26 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("salon_revenue_audit", "0017_salonrevenueauditoverview_petty_cash_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PettyCashAnnexure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "om_signature_available",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "reflecting_in_zenoti",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "supporting_document",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "authenticity",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("remark", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "revenue_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salon_revenue_audit.salonrevenueauditoverview",
                    ),
                ),
            ],
        ),
    ]
