# Generated by Django 4.1.3 on 2023-01-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon_revenue_audit", "0018_pettycashannexure"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonrevenueauditoverview",
            name="custom_verification_remark",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="salonrevenueauditoverview",
            name="physical_card_remark",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="salonrevenueauditoverview",
            name="physical_cash_remark",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
