# Generated by Django 3.2.13 on 2023-01-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon_revenue_audit', '0019_salonrevenueauditoverview_custom_verification_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashVerificationCashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_2000', models.CharField(blank=True, max_length=50, null=True)),
                ('count_500', models.CharField(blank=True, max_length=50, null=True)),
                ('count_200', models.CharField(blank=True, max_length=50, null=True)),
                ('count_100', models.CharField(blank=True, max_length=50, null=True)),
                ('count_50', models.CharField(blank=True, max_length=50, null=True)),
                ('count_20', models.CharField(blank=True, max_length=50, null=True)),
                ('count_10', models.CharField(blank=True, max_length=50, null=True)),
                ('count_5', models.CharField(blank=True, max_length=50, null=True)),
                ('count_2', models.CharField(blank=True, max_length=50, null=True)),
                ('count_1', models.CharField(blank=True, max_length=50, null=True)),
                ('count_50p', models.CharField(blank=True, max_length=50, null=True)),
                ('revenue_audit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salon_revenue_audit.salonrevenueauditoverview')),
            ],
        ),
    ]
