# Generated by Django 4.1.3 on 2023-01-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon_revenue_audit", "0020_cashverificationcashcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonauditrepeatedquestion",
            name="checklist_series",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="salonauditrepeatedquestion",
            name="tab_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
