# Generated by Django 4.1.3 on 2023-02-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon_revenue_audit", "0023_auto_20230131_1723"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hygieneannexure",
            name="sample_dates",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
