# Generated by Django 4.1.3 on 2023-02-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon_revenue_audit", "0024_alter_hygieneannexure_sample_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="hygieneannexure",
            name="evidence",
            field=models.FileField(blank=True, null=True, upload_to="media"),
        ),
    ]
