# Generated by Django 3.2.13 on 2023-02-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon_revenue_audit', '0025_hygieneannexure_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonCyberSecurityAnnexure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_area', models.CharField(blank=True, max_length=500, null=True)),
                ('zenoti_login_id', models.CharField(blank=True, max_length=500, null=True)),
                ('used_by', models.CharField(blank=True, max_length=500, null=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='media')),
                ('compliance', models.CharField(blank=True, max_length=500, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('revenue_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salon_revenue_audit.salonrevenueauditoverview')),
            ],
        ),
    ]
