# Generated by Django 3.2.13 on 2023-01-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_revenue_audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicrevenueauditoverview',
            name='audit_period',
        ),
        migrations.AddField(
            model_name='clinicrevenueauditoverview',
            name='audit_period_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicrevenueauditoverview',
            name='audit_period_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
