# Generated by Django 3.2.13 on 2023-02-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_revenue_audit', '0005_alter_clinicnotredeemedannexure_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinichygienecheckannexure',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
