# Generated by Django 4.1.3 on 2023-02-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corporate_audit", "0002_remove_corporateauditdetail_client_journey_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corporateauditoverview",
            name="amount_redeemed",
        ),
        migrations.RemoveField(
            model_name="corporateauditoverview",
            name="cost_of_service",
        ),
        migrations.RemoveField(
            model_name="corporateauditoverview",
            name="paid_in_cash",
        ),
        migrations.RemoveField(
            model_name="corporateauditoverview",
            name="payment_mode",
        ),
    ]
